const $=id=>document.getElementById(id);const authBox=$("authBox"),dashboard=$("dashboard");
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function msg(el,t,err=false){el.textContent=t;el.className="message "+(err?"error":"success")}
async function refresh(){const {data}=await supabaseClient.auth.getSession();const s=data.session;authBox.hidden=!!s;dashboard.hidden=!s;if(s){$("userEmail").textContent=s.user.email;loadMine()}}
$("authForm").addEventListener("submit",async e=>{e.preventDefault();msg($("authMessage"),"Connexion...");const {error}=await supabaseClient.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error){msg($("authMessage"),error.message,true);return}$("authForm").reset();refresh()});
$("signup").addEventListener("click",async()=>{const email=$("email").value.trim(),password=$("password").value;if(!email||password.length<6){msg($("authMessage"),"Entre un email et un mot de passe d'au moins 6 caractères.",true);return}msg($("authMessage"),"Création du compte...");const {data,error}=await supabaseClient.auth.signUp({email,password});if(error){msg($("authMessage"),error.message,true);return}if(data.session)refresh();else msg($("authMessage"),"Compte créé. Vérifie ton email si une confirmation est demandée, puis connecte-toi.")});
$("logout").addEventListener("click",async()=>{await supabaseClient.auth.signOut();refresh()});
function toDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
$("productForm").addEventListener("submit",async e=>{e.preventDefault();const {data:s}=await supabaseClient.auth.getSession();const user=s.session?.user;if(!user){msg($("productMessage"),"Connecte-toi.",true);return}const file=$("image").files[0];if(!file){msg($("productMessage"),"Choisis une photo.",true);return}if(file.size>2*1024*1024){msg($("productMessage"),"Photo trop grande : maximum 2 Mo.",true);return}try{msg($("productMessage"),"Ajout...");const image=await toDataURL(file);const product={user_id:user.id,name:$("name").value.trim(),category:$("category").value,price:$("price").value.trim()||null,description:$("description").value.trim(),image_url:image,affiliate_link:$("link").value.trim()};const {error}=await supabaseClient.from("products").insert(product);if(error)throw error;$("productForm").reset();msg($("productMessage"),"✅ Produit ajouté en ligne !");loadMine()}catch(e){msg($("productMessage"),e.message,true)}});
async function loadMine(){const {data:s}=await supabaseClient.auth.getSession();const user=s.session?.user;if(!user)return;const {data,error}=await supabaseClient.from("products").select("id,name,category,price,image_url").eq("user_id",user.id).order("created_at",{ascending:false});const list=$("adminProducts");if(error){list.innerHTML=`<p class="message error">${esc(error.message)}</p>`;return}list.innerHTML=data.length?"":'<p class="muted">Aucun produit ajouté.</p>';data.forEach(p=>{const d=document.createElement("div");d.className="admin-item";d.innerHTML=`<img src="${p.image_url}" alt=""><div><b>${esc(p.name)}</b><small>${esc(p.category)}${p.price?" · "+esc(p.price):""}</small></div><button type="button" class="delete" data-id="${p.id}">Supprimer</button>`;list.appendChild(d)});list.querySelectorAll(".delete").forEach(b=>b.onclick=async()=>{if(!confirm("Supprimer ce produit ?"))return;const {error}=await supabaseClient.from("products").delete().eq("id",b.dataset.id);if(error)alert(error.message);else loadMine()})}
supabaseClient.auth.onAuthStateChange(()=>refresh());refresh();